### ISSUE TITLE
不知道哪里导入文件

### ISSUE THREAD

**Issue by Crazy59** [SongKaixiang/Python-Combine-WeChat-and-AliPay-Billing-Details#1]
你好，我不知道哪里导入文件，能不能教教我

**Comment by SongKaixiang** [comment]
你好，修改文件中一下路径即可，替换成你的微信账单文件，支付宝账单文件和想保存的文件。
    path_wx = 'G:/事务/账本/下载下的/微信/微信支付账单(20200101-20200401)/微信支付账单(20200101-20200401).csv'
    path_zfb = 'G:/事务/账本/下载下的/支付宝/alipay_record_20200706_1143_1.csv'
    save_path = 'G:/事务/账本/last.xlsx'

**Comment by skx6** [comment]
> 
> 
> 你好，我不知道哪里导入文件，能不能教教我

你好，修改文件中一下路径即可，替换成你的微信账单文件，支付宝账单文件和想保存的文件。
path_wx = 'G:/事务/账本/下载下的/微信/微信支付账单(20200101-20200401)/微信支付账单(20200101-20200401).csv'
path_zfb = 'G:/事务/账本/下载下的/支付宝/alipay_record_20200706_1143_1.csv'
save_path = 'G:/事务/账本/last.xlsx'
